# Generated by Django 3.0.4 on 2020-03-24 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_firstname', models.CharField(max_length=255)),
                ('patient_lastname', models.CharField(max_length=255)),
                ('patient_email', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('access_code_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(verbose_name='order date')),
                ('status', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=1023)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pillapp.Patient')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pillapp.Pharmacy')),
            ],
        ),
    ]
