# Generated by Django 3.0.4 on 2020-03-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
