# Generated by Django 3.0.4 on 2020-03-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0002_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_email',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_phone',
            field=models.CharField(default='555-555-5555', max_length=20),
            preserve_default=False,
        ),
    ]
